version: "3"

services:
  db:
    image: mysql:8.0.20
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: db1
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
