zookeeper:
  image: jplock/zookeeper:3.4.6
  ports:
    - "2181:2181"

kafka:
  image: wurstmeister/kafka:0.8.2.1
  ports:
    - "9092:9092"
  links:
    - zookeeper
  environment:
    KAFKA_ADVERTISED_HOST_NAME: localhost
    KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
